routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => ['auth']], function () {
    Route::resource('account', 'AccountController');
    Route::resource('bathrooms', 'BathroomController');
    Route::resource('jobs', 'JobController');
    Route::resource('organisations', 'OrganisationController');
    Route::resource('users', 'UserController');
    Route::resource('dash', 'DashController');
    Route::resource('reports', 'ReportController');
    Route::resource('sites', 'SiteController');
    
    });
Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');

app/Bathroom.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\Models\Media;

class Bathroom extends Model implements HasMedia
{
    use HasMediaTrait;
    
    public function job() {
        return $this->hasMany('App\Job');
    }

    public function report() {
        return $this->hasMany('App\Report');
    }

    public function site() {
        return $this->belongsTo('App\Site');
    }

    protected $fillable = [
        'sinks', 'toilets', 'site_id',
    ];

    public function registerMediaConversions(Media $media = null)
    {
        $this->addMediaConversion('small')
            ->width(150)
            ->height(150);
    }
}

app/Http/Controllers/BathroomController.php
<?php

namespace App\Http\Controllers;

use App\Bathroom;
use App\Site;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;

class BathroomController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        Log::info('siteID' . $request->get('site_id'));
        $bathrooms = Bathroom::where('site_id', $request->get('site_id'))->get();
        Log::info('bathrooms' . $bathrooms);
        return view('Bathroom.index', compact('bathrooms'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $bathrooms = Bathroom::all();
        $sites = Site::all();
        return view('Bathroom.addBathroom', compact('bathrooms', 'sites'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validate
        $request->validate([
            'sinks' => 'integer|required',
            'toilets' => 'integer|required',
        ]);

        //store
        $bathroom = Bathroom::firstOrNew([
            'sinks' => $request->get('sinks'),
            'toilets' => $request->get('toilets'),
            'site_id' => $request->get('site'),
        ]);

        if($request->hasFile('file1') && $request->file('file1')->isValid()){
            $bathroom->addMediaFromRequest('file1')->toMediaCollection('bathroom_images');
        }

        if($request->hasFile('file2') && $request->file('file2')->isValid()){
            $bathroom->addMediaFromRequest('file2')->toMediaCollection('bathroom_images');
        }

        if($request->hasFile('file3') && $request->file('file3')->isValid()){
            $bathroom->addMediaFromRequest('file3')->toMediaCollection('bathroom_images');
        }
        $bathroom->save();
        return redirect('/sites');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Bathroom  $bathroom
     * @return \Illuminate\Http\Response
     */
    public function show(Bathroom $bathroom)
    {
        return view('Bathroom.bathroomDetails', compact('bathroom'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Bathroom  $bathroom
     * @return \Illuminate\Http\Response
     */
    public function edit(Bathroom $bathroom)
    {
        return view('Bathroom.editBathroom', compact('bathroom'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Bathroom  $bathroom
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Bathroom $bathroom)
    {
        //validate
        $request->validate([
            'sinks' => 'required|integer',
            'toilets' => 'required|integer'
        ]);
        //update
        $bathroom->sinks = $request->get('sinks');
        $bathroom->toilets = $request->get('toilets');
        //image
        $bathroom->save();
        if($request->hasFile('file1') && $request->file('file1')->isValid()){
            $bathroom->addMediaFromRequest('file1')->toMediaCollection('bathroom_images');
            Log::info('Data');
        }
        $bathroom->save();
        return redirect('/sites');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Bathroom  $bathroom
     * @return \Illuminate\Http\Response
     */
    public function destroy(Bathroom $bathroom)
    {
        $bathroom->delete();
        return redirect('/sites');
    }
}

resources/views/Bathroom/addBathroom.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">New Bathroom</h1>
        <div>
        @if ($errors->any())
            <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
            </div><br/>
        @endif
            <form action="{{route('bathrooms.store')}}" method="POST">
                @csrf
                <label for="toilets">Toilets</label>
                <input type="number" name="toilets" class="form-control"/><br/>
                <label for="sinks">Sinks</label>
                <input type="number" name="sinks" class="form-control"/><br/>
                <label for="site">Site</label>
                <select name="site">
                    @foreach ($sites as $site)
                        <option value="{{$site->id}}">{{$site->location}}</option>
                    @endforeach
                </select><br/><br/>
                <input type="file" name="file1"><br/><br/>
                <input type="file" name="file1"><br/><br/>
                <input type="file" name="file1"><br/><br/>
                <button class="btn btn-secondary" type="submit">New Bathroom</button>
            </form>
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        </div>
    </div>
</div>
@endsection

resources/views/Bathroom/bathroomDetails.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Details</h1>
        <div>
        @if ($errors->any())
            <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
            </div><br/>
        @endif
            <table><thead><tr><th>ID</th>
                <th>&nbsp;&nbsp;Site</th>
                <th>&nbsp;&nbsp;Organisation</th>
                <th>&nbsp;&nbsp;Sinks</th>
                <th>&nbsp;&nbsp;Toilets</th>
                <th>&nbsp;&nbsp;Images</th>
            </tr></thead><tbody><tr><td>{{$bathroom->id}}</td>
                <td>&nbsp;&nbsp;{{$bathroom->site->location}}</td>
                <td>&nbsp;&nbsp;{{$bathroom->site->organisation->name}}</td>
                <td>&nbsp;&nbsp;{{$bathroom->sinks}}</td>
                <td>&nbsp;&nbsp;{{$bathroom->toilets}}</td>

                @if($bathroom->getMedia('bathroom_images') != null)
                    @foreach ($bathroom->getMedia('bathroom_images') as $image)
                        <td> &nbsp;&nbsp;&nbsp;<a href="{{ $image->getUrl()}}"> <img src="{{ $image->getUrl('small') }}"> </a>  </td>
                    @endforeach
                @endif     
                </tr></tbody></table>
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        </div>
    </div>
</div>
@endsection

resources/views/Bathroom/editBathroom.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Edit Bathroom Details</h1>
        <div>
        @if ($errors->any())
            <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
            </div><br/>
        @endif
            <form action="{{route('bathrooms.update', $bathroom->id)}}" method="POST">
                @method('PATCH')
                @csrf
                <div>
                    <label for="toilets">Toilets</label>
                    <input type="number" name="toilets" class="form-control" value="{{$bathroom->toilets}}">
                </div>
                <div>
                    <label for="sinks">Sinks</label>
                    <input type="number" name="sinks" class="form-control" value="{{$bathroom->sinks}}">
                </div>
                <input type="file" name="file1" /> <br/><br/>
                <button type="submit" class="btn btn-secondary">Update</button>
            </form>
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        </div>
    </div>
</div>
@endsection

resources/views/Bathroom/index.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Bathrooms</h1>
        <div>
        @if ($errors->any())
            <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
            </div><br/>
        @endif
            <table><thead><tr>
                <th>ID</th>
            </tr></thead><tbody>
                @foreach($bathrooms as $bathroom)
                <tr><td>{{$bathroom->id}}</td>
                    <td><a href="{{route('bathrooms.show', $bathroom->id)}}" class="btn btn-primary">Show Details</a></td>
                    @role('Manager')
                        <td><a href="{{route('bathrooms.edit', $bathroom->id)}}" class="btn btn-primary">Edit</a></td>
                        <td><form action="{{route('bathrooms.destroy', $bathroom->id)}}" method="POST">
                        @csrf
                        @method('DELETE')
                        <button class="btn btn-danger" type="submit"> Delete</button></form></td>
                    @endrole   
            </tr>
            @endforeach</tbody>
        </table>

        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        </div>
    </div>
</div>
@endsection