routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => ['auth']], function () {
    Route::resource('account', 'AccountController');
    Route::resource('bathrooms', 'BathroomController');
    Route::resource('jobs', 'JobController');
    Route::resource('organisations', 'OrganisationController');
    Route::resource('users', 'UserController');
    Route::resource('dash', 'DashController');
    Route::resource('reports', 'ReportController');
    Route::resource('sites', 'SiteController');
    
    });
Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');

app/Organisation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Organisation extends Model
{

    public function site() {
        return $this->hasMany('App\Site');
    }

    protected $fillable = [
        'name', 'contact_number'
    ];
}

app/Http/Controllers/OrganisationController.php
<?php

namespace App\Http\Controllers;

use App\Organisation;
use Illuminate\Http\Request;

class OrganisationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $organisations = Organisation::paginate(5);

        return view('Organisation.organisationIndex', compact('organisations'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $organisations = Organisation::all();
        return view('Organisation.addOrganisation', compact('organisations'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //Validate
        $request->validate([
            'name' => 'required|string',
            'contact_number' => 'required|string|max:12'
        ]);

        //New
        $organisation = Organisation::firstOrNew([
            'name' => $request->get('name'),
            'contact_number' => $request->get('contact_number'),
        ]);
        $organisation->save();
        return redirect('/organisations')->with('Organisation created');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Organisation  $organisation
     * @return \Illuminate\Http\Response
     */
    public function show(Organisation $organisation)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Organisation  $organisation
     * @return \Illuminate\Http\Response
     */
    public function edit(Organisation $organisation)
    {
        return view('Organisation.editOrganisation', compact('organisation'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Organisation  $organisation
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Organisation $organisation)
    {
        $request->validate([
            'name' => 'required|string|max:255',
            'contact_number' => 'required|string|max:12',
            ]);
        $organisation->name = $request->get('name');
        $organisation->contact_number = $request->get('contact_number');
        $organisation->save();

        return redirect('organisations');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Organisation  $organisation
     * @return \Illuminate\Http\Response
     */
    public function destroy(Organisation $organisation)
    {
        $organisation->delete();
    }
}

resources/views/Organisation/addOrganisation.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Create Organisation</h1>
        <div>
        @if ($errors->any())
            <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
            </div><br/>
        @endif
        @role('Manager')
            <form method="POST" action="{{route('organisations.store')}}">
                @csrf
                <div class="form-group">
                    <label for="name">Name:</label>
                    <input type="text" class="form-control" name="name"/>
                </div>

                <div class="form-group">
                    <label for="contact_number">Contact Number:</label>
                    <input type="string" class="form-control" name="contact_number"/>
                </div>
                <button type="submit" class="btn btn-primary">Add Organisation</button>
            </form>
        @endrole
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        </div>
    </div>
</div>
@endsection

resources/views/Organisation/editOrganisation.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Edit Organisation Details</h1>
        <div>
        @if ($errors->any())
            <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
            </div><br/>
        @endif
        @role('Manager')
        <form method="post" action="{{ route('organisations.update', $organisation->id)}}">
            @method('PATCH')
            @csrf
            <div class="form-group">
                <label for="name">name:</label>
                <input type="text" class="form-control" name="name" value="{{ $organisation->name }}">
            </div>
            <div class="form-group">
                <label for="contact_number">Contact Number:</label>
                <input type="text" class="form-control" name="contact_number" value="{{ $organisation->contact_number }}">
            </div>
            <button type="submit" class="btn btn-secondary">Update</button>
        </form>
        @endrole

        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        </div>
    </div>
</div>
@endsection

resources/views/Organisation/organisationIndex.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Organisations</h1>
        <div>
        @if ($errors->any())
            <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
            </div><br/>
        @endif
        @role('Manager')
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Contact Number</th>
                </tr>
            </thead>
            <div><a style="margin:19px;" href="{{route('organisations.create')}}" class="btn btn-primary">New Organisation</a></div>
            <tbody>
                @foreach ($organisations as $organisation)
                    <tr>
                        <td>{{ $organisation->name }}</td>
                        <td>{{ $organisation->contact_number  }}</td>
                        <td><a href="{{route('organisations.edit', $organisation->id)}}" class="btn btn-primary">Edit</a></td>
                        <td><form action="{{route('organisations.destroy', $organisation->id)}}" method="POST">
                        @csrf
                        @method('DELETE')
                        <button class="btn btn-primary" type="sumbit"> Delete</button></form></td>
                    </tr> 
                @endforeach
            </tbody>
        </table>
    @endrole
    <div class="row">
        <div class="col-12 d-flex justify-content-center pt-4">
            {{$organisations->links()}}
        </div>
    </div>
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        </div>
    </div>
</div>
@endsection