routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => ['auth']], function () {
    Route::resource('account', 'AccountController');
    Route::resource('bathrooms', 'BathroomController');
    Route::resource('jobs', 'JobController');
    Route::resource('organisations', 'OrganisationController');
    Route::resource('users', 'UserController');
    Route::resource('dash', 'DashController');
    Route::resource('reports', 'ReportController');
    Route::resource('sites', 'SiteController');
    
    });
Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\Models\Media;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable implements HasMedia, MustVerifyEmail
{
    use Notifiable; use HasRoles; use HasMediaTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'address', 'contact_num',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    public function job() {
        return $this->hasMany('App\Job');
    }

    public function registerMediaConversions(Media $media = null)
    {
        $this->addMediaConversion('thumb')
            ->width(50)
            ->height(50);
           
        $this->addMediaConversion('square')
            ->width(280)
            ->height(312)
            ->sharpen(10);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Job;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Pagination\Paginator;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Support\Collection;
use Log;
class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $filter = $request->get('filter');
        $assignedUsers = array();
        $unassignedUsers = array();
        $jobs = Job::all();

        foreach($jobs as $job){
            if($job->user_id !=null){
                array_push($assignedUsers, $job->user); 
            }
        }
        $users = User::role('staff')->get();
        foreach($users as $user){
            if(!in_array($user, $assignedUsers)){
                array_push($unassignedUsers, $user);
            }
        }
        //$users = User::whereHas("roles", function(Builder $q) {$q->where("name", "staff"); })->get();

        if($filter == null || $filter == 'all'){
            $users = User::paginate(5);
        }else if($filter == 'assigned'){
            $users = $this->paginate($assignedUsers);
        }else if($filter == 'unassigned'){
            $users = $this->paginate($unassignedUsers);
        }
        if(count($users) > 0){
            $filter = $request->get('filter');
        }else{
            $filter = "empty";
        }
        return view('User.userIndex', compact('users', 'filter'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users = User::all();
        return view('User.createUser', compact('users'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|string|max:255',
            'password' => 'required|string|min:8',
            'address' => 'required|string|min:5',
            'contact_num' => 'required|numeric|min:11',
        ]);
        $user = User::firstOrNew([
            'email' => $request['email'],
        ]);
        Log::info('Address Check : ' . $request->get('address'));

        $user->fill([
            'name' => $request->name,
            'address' => $request->address,
            'contact_num' => $request->contact_num,
            'password' => Hash::make($request->password),
            ]);
            $user->assignRole('staff'); 
            $user->save();

        return redirect('/users')->with('User added');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Site  $site
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Site  $site
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('User.editUser', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Site  $site
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|string|max:255',
            'address' => 'required|string|min:5',
            'contact_num' => 'required|numeric|min:11',
        ]);

        $user->name = $request->get('name');
        $user->email = $request->get('email');
        $user->address = $request->get('address');
        $user->contact_num = $request->get('contact_num');
        $user->save();

        $user->assignRole('staff'); 
        return redirect('/users')->with('updated user');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Site  $site
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();
        return redirect('/users')->with('User deleted!');
    }

    public function paginate($items, $perPage = 5, $page = null, $options = [])
    {
    $page = $page ?: (Paginator::resolveCurrentPage() ?: 1);
    $items = $items instanceof Collection ? $items : Collection::make($items);
    return new LengthAwarePaginator($items->forPage($page, $perPage), $items->count(), $perPage, $page, $options);
    }
}

resources/views/User/createUser.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Create User</h1>
        <div>
        @if ($errors->any())
            <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
            </div><br/>
        @endif
        @role('Manager')
        <form method="post" action="{{ route('users.store') }}">
            @csrf
            <div class="form-group">
                <label for="name">name:</label>
                <input type="text" class="form-control" name="name" />
            </div>
            <div class="form-group">
                <label for="email">Email:</label>
                <input type="email" class="form-control" name="email"/>
            </div>
            <div class="form-group">
                <label for=password>Password</label>
                <input type="password" class="form-control" name="password"/>
            <div>
                <label for="contactNumber">Contact Number</label>
                <input type="string" class="form-control" name="contact_num"/>
            </div>
            <div>
                <label for="address">Address</label>
                <input type="string" class="form-control" name="address"/>
            </div>
            <br/><br/>
            <button type="submit" class="btn btn-secondary">Add User</button>
        </form>
    @endrole
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        </div>
    </div>
</div>
@endsection

resources/views/User/editUser.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Edit User Details</h1>
        <div>
        @if ($errors->any())
            <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
            </div><br/>
        @endif
        @role('Manager')
        <form method="post" action="{{ route('users.update', $user->id)}}">
            @method('PATCH')
            @csrf
            <div class="form-group">
                <label for="name">name:</label>
                <input type="text" class="form-control" name="name" value="{{ $user->name }}">
            </div>
            <div class="form-group">
                <label for="email">Email:</label>
                <input type="email" class="form-control" name="email" value="{{$user->email}}">
            </div>
            <div class="form-group">
                <label for="address">address:</label>
                <input type="text" class="form-control" name="address" value="{{ $user->address }}">
            </div>
            <div class="form-group">
                <label for="contact_num">Contact Number:</label>
                <input type="text" class="form-control" name="contact_num" value="{{ $user->contact_num }}">
            </div>
            <button type="submit" class="btn btn-secondary">Add User</button>
        </form>
        @endrole

        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        </div>
    </div>
</div>
@endsection

resources/views/User/userIndex.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Users</h1>
        <div>
        @if ($errors->any())
            <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
            </div><br/>
        @endif
        <div id="msg"> </div>
        <div id="newdiv"><h6>data</h6></div>
        @role('Manager')
        <div><a style="margin: 19px;" href ="{{ route('users.create') }}" class="btn btn-primary">New User</a>
            <a style="margin: 19px;" href ="{{ route('users.index', ['filter'=> 'all']) }}" class="btn btn-primary">All</a>
            <a style="margin: 19px;" href ="{{ route('users.index', ['filter'=> 'assigned']) }}" class="btn btn-primary">Assigned</a>
            <a style="margin: 19px;" href ="{{ route('users.index', ['filter'=> 'unassigned']) }}" class="btn btn-primary">Unassigned</a></div>
            <input type="text" id="filterInput" placeholder="search">
            @if($filter != 'empty')
          
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Address</th>
                            <th>Contact Number</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($users as $user)
                            <tr>
                                <td>{{ $user->name }}</td>
                                <td>{{ $user->email }}</td>
                                <td>{{ $user->address }}</td>
                                <td>{{ $user->contact_num }}</td>
                                <td><a href="{{route('users.edit', $user->id)}}" class="btn btn-primary">Edit</a></td>
                                <td><form action="{{route('users.destroy', $user->id)}}" method="POST">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger" type="submit"> Delete</button></form></td>   
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            @else
                <h1>No results matching Criteria</h1>
            @endif
        @endrole

        <div class="row">
            <div class="col-12 d-flex justify-content-center pt-4">
                {{$users->links()}}
            </div>
        </div>

        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        </div>
    </div>
</div>
@endsection