routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => ['auth']], function () {
    Route::resource('account', 'AccountController');
    Route::resource('bathrooms', 'BathroomController');
    Route::resource('jobs', 'JobController');
    Route::resource('organisations', 'OrganisationController');
    Route::resource('users', 'UserController');
    Route::resource('dash', 'DashController');
    Route::resource('reports', 'ReportController');
    Route::resource('sites', 'SiteController');
    
    });
Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');

app/Site.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Site extends Model
{
    public function bathroom() {
        return $this->hasMany('App\Bathroom');
    }

    public function organisation() {
        return $this->belongsTo('App\Organisation');
    }

    protected $fillable = [
        'location', 'organisation_id', 'password',
    ];
}

app/Http/Controllers/SiteController.php
<?php

namespace App\Http\Controllers;

use App\Organisation;
use App\Site;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;


class SiteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $sites = Site::Paginate(5);
        return view('Site.siteIndex', compact('sites'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $sites = Site::all();
        $organisations = Organisation::all();
        return view('Site.createSite', compact('sites', 'organisations'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Log::info('message');
        //Validate
        $request->validate([
            'location' => 'required|string'
        ]);

        //Store
        $site = Site::firstOrNew([
            'location' => $request->get('location'),
            'organisation_id' => $request->get('organisation'),
            ]);
        $site->save();
        Log::info('site check' . $site);
        return redirect('/sites')->with('Site created');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Site  $site
     * @return \Illuminate\Http\Response
     */
    public function show(Site $site)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Site  $site
     * @return \Illuminate\Http\Response
     */
    public function edit(Site $site)
    {
        return view('Site.editSite', compact('site'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Site  $site
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Site $site)
    {
        //Validate
        $request->validate([
            'location' => 'required|string'
        ]);

        //Update
        $site->location = $request->get('location');
        $site->save();
        return redirect('/sites');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Site  $site
     * @return \Illuminate\Http\Response
     */
    public function destroy(Site $site)
    {
        $site->delete();
        return redirect('/sites');
    }
}

resources/views/Site/createSite.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Create Site</h1>
        <div>
        @if ($errors->any())
            <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
            </div><br/>
        @endif
        @role('Manager')
            <form method="POST" action="{{ route('sites.store') }}">
                @csrf
                <div>
                    <label for="location">Location</label>
                    <input type="text" name="location" class="form-control"/>
                </div><br/>
                <div>
                    <label name="organisation">Organisation</label>&nbsp;&nbsp;&nbsp;
                    <select name="organisation">
                        @foreach ($organisations as $organisation)
                            <option value="{{$organisation->id}}">{{$organisation->name}}</option>
                        @endforeach
                    </select>
                </div><br/>
                <button type="submit" class="btn btn-secondary">Create</button>
            </form>
        @endrole
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        </div>
    </div>
</div>
@endsection

resources/views/Site/editSite.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Edit Site</h1>
        <div>
        @if ($errors->any())
            <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
            </div><br/>
        @endif
        @role('Manager')
            <form method="POST" action="{{ route('sites.update', $site->id) }}">
                @method('PATCH')
                @csrf
                <div>
                    <label for="location">Location</label>
                    <input type="text" name="location" class="form-control" value="{{$site->location}}"/>
                </div><br/>
                <button type="submit" class="btn btn-secondary">Update</button>
            </form>
        @endrole
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        </div>
    </div>
</div>
@endsection

resources/views/Site/siteIndex.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Sites</h1>
        <div>
        @if ($errors->any())
            <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
            </div><br/>
        @endif
        @role('Manager')
            <a href="{{route('sites.create')}}" class="btn btn-primary">New Site</a>
            <a href="{{route('bathrooms.create')}}" class="btn btn-primary">New Bathroom</a>
        @endrole
        <table>
            <thead>
                <tr>
                    <th>Location</th>
                    <th>Organisation</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($sites as $site )
                    <tr>
                        <td>{{$site->location}}</td>
                        <td>{{$site->organisation->name}}</td>
                        <td><a href="{{route('bathrooms.index', ['site_id'=>$site->id])}}" class="btn btn-primary">View Bathrooms</a></td>
                        @role('Manager')
                            <td><a href="{{route('sites.edit', $site->id)}}" class="btn btn-primary">Edit</a></td>
                            <td><form action="{{route('sites.destroy', $site->id)}}" method="POST">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger" type="submit"> Delete</button></form></td>
                        @endrole   
                    </tr>
                @endforeach
            </tbody>
        </table>
        <div class="row">
            <div class="col-12 d-flex justify-content-center pt-4">
                {{$sites->links()}}
            </div>
        </div>
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        </div>
    </div>
</div>
@endsection